### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by DylanHobbs** [TrapScan/TrapScan#94]
- [ ] try https://openlayers.org/
- [ ] figure out what to do with it - "I can't find the trap, show map" feature?
- [ ] Design screens

**Comment by KurtisPapple** [comment]
This is definitely needed - speaking with the two that have taken over botanic gardens, they are now having to use two apps at once which is a real pain. They literally only using trap NZ because it has a map.

And it's just that starting point trying to find traps on a line that you're not familiar with.

Must be extremely lightweight and simple. A basic map showing basic topography would be great and large indicators.

Maybe only show the five closest traps at a time - could that improve performance on the phone? If we limited it like nearby traps, then we could link from nearby traps to the map. I click on a nearby traps and then you'd have the option "show on map"

**Comment by DylanHobbs** [comment]
Devnotes 

- Possibly look at using 2 separate maps  
- One for "desktop" view focused on creating traps / trap lines / moving and editing
- One for mobile which is very restrcited and only really to be used to find out where the next trap is located
